/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { AlertCircle, ArrowLeft, ArrowUpLeft, Boxes, CalendarClock, Check, CircleDollarSign, CreditCard, Plus, ReceiptText, RefreshCw, TrendingUp } from "lucide-react";
import { listInvoices } from "../api/invoices";
import { listProducts } from "../api/products";
import { getSalesSummary, getProfitLoss, getInventoryValue } from "../api/reports";
import { getStockAlerts } from "../api/warehouses";
import { formatDate, formatMoney, numberValue, unwrapData, apiErrorMessage } from "../utils/pageHelpers";

const today = new Date().toISOString().slice(0, 10); const monthStart = `${today.slice(0, 8)}01`;
export default function DashboardPage({ onCreateInvoice, onCreateInternalInvoice, onCreateExpense }) {
  const [data, setData] = useState({ invoices: [], products: [], sales: {}, profit: {}, inventory: {}, alerts: {} }); const [state, setState] = useState({ loading: true, error: "" });
  const load = async () => { setState({ loading: true, error: "" }); try { const [invoices, products, sales, profit, inventory, alerts] = await Promise.all([listInvoices({ limit: 100 }), listProducts({ limit: 100 }), getSalesSummary({ from: monthStart, to: today }), getProfitLoss({ from: monthStart, to: today }), getInventoryValue({ asOf: today }), getStockAlerts({})]); setData({ invoices: unwrapData(invoices), products: unwrapData(products), sales, profit, inventory, alerts }); setState({ loading: false, error: "" }); } catch (e) { setState({ loading: false, error: apiErrorMessage(e) }); } };
  useEffect(() => { load(); }, []);
  const due = data.invoices.filter((i) => ["credit", "partially_paid", "overdue"].includes(i.paymentStatus)); const lowStock = data.alerts?.lowStock || []; const sales = data.sales?.totals?.sales; const cards = [{ label: "إجمالي المبيعات", value: sales, unit: "ج.م", icon: TrendingUp, tone: "red" }, { label: "صافي الأرباح", value: data.profit?.netProfit, unit: "ج.م", icon: CircleDollarSign, tone: "green" }, { label: "قيمة المخزون", value: data.inventory?.totalValue, unit: "ج.م", icon: Boxes, tone: "blue" }, { label: "المبالغ المستحقة", value: due.reduce((sum, i) => sum + Math.max(numberValue(i.total) - numberValue(i.paidAmount), 0), 0), unit: "ج.م", icon: CreditCard, tone: "amber", extra: `${due.length} فاتورة` }];
  return <div className="page-container">{state.error && <div className="page-error mb-4">{state.error}</div>}<section className="welcome-strip"><div><span className="eyebrow">ملخص اليوم</span><h2>كل أرقامك المهمة في مكان واحد</h2><p>البيانات محدثة مباشرة من الباك.</p></div><div className="welcome-meta"><span className="live-dot" /> آخر تحديث الآن <button onClick={load}>تحديث <RefreshCw size={14} /></button></div></section><section className="stats-grid">{cards.map((card) => <StatCard key={card.label} {...card} loading={state.loading} />)}</section><section className="main-grid"><CashFlowPanel sales={sales} profit={data.profit?.netProfit} /><aside className="alerts-column"><AlertsPanel lowStock={lowStock} due={due} onCreateInvoice={onCreateInvoice} onCreateInternalInvoice={onCreateInternalInvoice} onCreateExpense={onCreateExpense} /></aside></section><section className="panel invoices-panel"><div className="panel-heading"><div><span className="eyebrow">آخر الحركات</span><h2>الفواتير الأخيرة</h2></div><button className="text-link" onClick={load}>تحديث <RefreshCw size={14} /></button></div><div className="table-wrap"><table><thead><tr><th>رقم الفاتورة</th><th>الطرف</th><th>النوع</th><th>المبلغ</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{data.invoices.slice(0, 6).map((invoice) => <tr key={invoice._id}><td><strong className="invoice-number">{invoice.invoiceNumber}</strong></td><td>{invoice.party?.name || "—"}</td><td><span className="type-chip">{invoice.invoiceType === "sale" ? "بيع" : "شراء"}</span></td><td><strong>{formatMoney(invoice.total)}</strong> <small>ج.م</small></td><td><span className={`status-pill ${invoice.paymentStatus === "paid" ? "status-paid" : invoice.paymentStatus === "partially_paid" ? "status-partial" : "status-due"}`}>{invoice.paymentStatus || invoice.status}</span></td><td className="muted-cell">{formatDate(invoice.issueDate)}</td></tr>)}</tbody></table>{!state.loading && !data.invoices.length && <div className="p-8 text-center text-xs text-slate-400">لا توجد فواتير مسجلة.</div>}</div></section><section className="bottom-note"><div className="note-icon"><Check size={17} /></div><div><strong>البيانات الحية مفعلة</strong><span>يتم عرض الأرقام والعمليات من قاعدة البيانات مباشرة.</span></div></section></div>;
}
function StatCard({ label, value, unit, icon: Icon, tone, extra, loading }) { return <article className={`stat-card stat-${tone}`}><div className="stat-card-top"><span className="stat-icon"><Icon size={20} /></span><button className="more-button">•••</button></div><p>{label}</p><div className="stat-value"><strong>{loading ? "—" : formatMoney(value)}</strong><span>{unit}</span></div><div className="stat-footer"><span className="stat-change">{extra || "هذا الشهر"}</span></div></article>; }
function CashFlowPanel({ sales, profit }) { return <section className="panel cashflow-panel"><div className="panel-heading"><div><span className="eyebrow">نظرة سريعة</span><h2>ملخص الأداء المالي</h2></div><TrendingUp size={20} className="text-[#df2431]" /></div><div className="cashflow-summary"><div><span className="legend-dot inflow" /><span>المبيعات</span><strong>{formatMoney(sales)} ج.م</strong><small className="positive"><ArrowUpLeft size={12} /> الفترة الحالية</small></div><div><span className="legend-dot outflow" /><span>صافي الربح</span><strong>{formatMoney(profit)} ج.م</strong><small><ArrowUpLeft size={12} /> بعد المصروفات</small></div></div><div className="mt-8 rounded-xl bg-slate-50 p-6 text-center text-xs text-slate-500">التفاصيل الشهرية متاحة في صفحة التقارير.</div></section>; }
function AlertsPanel({ lowStock, due, onCreateInvoice, onCreateInternalInvoice, onCreateExpense }) { const alerts = [{ title: "فواتير تحتاج تحصيل", detail: `${due.length} فاتورة مستحقة أو جزئية`, value: `${formatMoney(due.reduce((sum, i) => sum + Math.max(numberValue(i.total) - numberValue(i.paidAmount), 0), 0))} ج.م`, tone: "red", Icon: AlertCircle }, { title: "منتجات قاربت على النفاد", detail: `${lowStock.length} تنبيه من المخزن`, value: "عرض التفاصيل", tone: "amber", Icon: Boxes }, { title: "تحديثات المخزون", detail: "تابعي حركة التوريد والبيع", value: "فتح المخازن", tone: "blue", Icon: CalendarClock }]; return <><section className="panel alerts-panel"><div className="panel-heading"><div><span className="eyebrow">يحتاج انتباهك</span><h2>التنبيهات</h2></div><span className="alert-count">{alerts.length}</span></div><div className="alerts-list">{alerts.map((alert) => <div className="alert-item" key={alert.title}><div className={`alert-icon alert-${alert.tone}`}><alert.Icon size={18} /></div><div className="alert-copy"><strong>{alert.title}</strong><span>{alert.detail}</span><button>{alert.value} <ArrowLeft size={13} /></button></div></div>)}</div></section><section className="quick-actions"><div><span className="eyebrow">اختصارات سريعة</span><h2>إنجاز أسرع</h2></div><button onClick={onCreateInvoice}><span><Plus size={18} /></span><strong>فاتورة جديدة</strong><small>بيع أو شراء</small></button><button onClick={onCreateInternalInvoice}><span><ReceiptText size={18} /></span><strong>فاتورة للمكتب</strong><small>صرف أصل من المخزون</small></button><button onClick={onCreateExpense}><span><ReceiptText size={18} /></span><strong>تسجيل مصروف</strong><small>إضافة حركة مالية</small></button></section></>; }
