import { useEffect, useState } from "react";
import { BarChart3, CalendarDays, FileDown, RefreshCw, TrendingUp, Warehouse } from "lucide-react";
import { getBalanceSheet, getGrossProfit, getInventoryValue, getInvoiceMargins, getProfitLoss } from "../api/reports";
import { apiErrorMessage, formatMoney, numberValue } from "../utils/pageHelpers";

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 8)}01`;
function reportValues(response) { const value = response?.data || response || {}; return { revenue: numberValue(value.revenue ?? value.sales ?? value.totalSales ?? value.income), cost: numberValue(value.costOfGoodsSold ?? value.cost ?? value.purchases), expenses: numberValue(value.expenses ?? value.totalExpenses), profit: numberValue(value.netProfit ?? value.grossProfit ?? value.profit), totalAssets: numberValue(value.totalAssets ?? value.assets), inventory: numberValue(value.inventoryValue ?? value.totalValue ?? value.value), invoices: numberValue(value.invoiceCount ?? value.totalInvoices) }; }
export default function ReportsPage() { const [range, setRange] = useState({ from: monthStart, to: today }); const [reports, setReports] = useState({}); const [state, setState] = useState({ loading: true, error: "" }); const load = async () => { setState({ loading: true, error: "" }); try { const query = { from: range.from, to: range.to }; const [pl, profit, inventory, balance, margins] = await Promise.all([getProfitLoss(query), getGrossProfit(query), getInventoryValue(query), getBalanceSheet(query), getInvoiceMargins(query)]); setReports({ pl: reportValues(pl), profit: reportValues(profit), inventory: reportValues(inventory), balance: reportValues(balance), margins: reportValues(margins) }); setState({ loading: false, error: "" }); } catch (error) { setState({ loading: false, error: apiErrorMessage(error) }); } }; // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { load(); }, []); const pl = reports.pl || {}; const profit = reports.profit || {}; const inventory = reports.inventory || {}; const balance = reports.balance || {}; return <div className="page-container !pt-7"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><span className="eyebrow">التحليل المالي</span><h2 className="!m-0 !text-[25px]">التقارير المالية</h2><p className="mt-2 text-xs text-slate-500">صورة واضحة للأرباح، التكاليف، قيمة المخزون والميزانية.</p></div><div className="flex flex-wrap items-center gap-2"><label className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs text-slate-500"><CalendarDays size={15} /><input type="date" value={range.from} onChange={(e) => setRange({ ...range, from: e.target.value })} /></label><span className="text-xs text-slate-400">إلى</span><input type="date" value={range.to} onChange={(e) => setRange({ ...range, to: e.target.value })} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs" /><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 hover:text-[#df2431]"><RefreshCw size={16} /></button></div></div>{state.error && <div className="mb-5 rounded-xl border border-red-100 bg-red-50 p-4 text-xs text-red-700">{state.error}</div>}<div className="mb-5 grid grid-cols-1 gap-3 md:grid-cols-4"><ReportCard icon={<TrendingUp size={18} />} label="صافي الربح" value={pl.profit || profit.profit} tone="green" /><ReportCard icon={<BarChart3 size={18} />} label="إجمالي المبيعات" value={pl.revenue} tone="red" /><ReportCard icon={<Warehouse size={18} />} label="قيمة المخزون" value={inventory.inventory} tone="blue" /><ReportCard icon={<FileDown size={18} />} label="إجمالي الأصول" value={balance.totalAssets} tone="amber" /></div><div className="grid grid-cols-1 gap-5 xl:grid-cols-2"><ReportPanel title="الأرباح والخسائر" rows={[["الإيرادات والمبيعات", pl.revenue], ["تكلفة المبيعات", pl.cost], ["المصروفات", pl.expenses], ["صافي الربح", pl.profit || profit.profit]]} loading={state.loading} /><ReportPanel title="الملخص المحاسبي" rows={[["إجمالي الأصول", balance.totalAssets], ["قيمة المخزون", inventory.inventory], ["عدد الفواتير", pl.invoices], ["هامش الربح", reports.margins?.profit]]} loading={state.loading} /></div></div>; }
function ReportCard({ icon, label, value, tone }) { const colors = { green: "border-emerald-100 bg-emerald-50 text-emerald-700", red: "border-red-100 bg-red-50 text-red-700", blue: "border-blue-100 bg-blue-50 text-blue-700", amber: "border-amber-100 bg-amber-50 text-amber-700" }; return <div className={`rounded-2xl border p-5 shadow-sm ${colors[tone]}`}><span className="mb-4 grid h-9 w-9 place-items-center rounded-xl bg-white/80">{icon}</span><span className="block text-[11px] text-slate-600">{label}</span><strong className="mt-2 block text-2xl text-slate-800">{formatMoney(value)} <small className="text-xs font-normal text-slate-400">ج.م</small></strong></div>; }
function ReportPanel({ title, rows, loading }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="!m-0 !text-[17px]">{title}</h2><span className="text-[10px] text-slate-400">حسب الفترة المحددة</span></div>{loading ? <div className="py-10 text-center text-xs text-slate-400">جارٍ تحميل التقرير...</div> : <div className="space-y-1">{rows.map(([label, value]) => <div key={label} className="flex items-center justify-between rounded-xl px-3 py-3 odd:bg-slate-50"><span className="text-xs text-slate-600">{label}</span><strong className="text-sm text-slate-800">{formatMoney(value)} <small className="text-[10px] font-normal text-slate-400">ج.م</small></strong></div>)}</div>}</section>; }
