import { useState } from "react";
import { X } from "lucide-react";
import { createCustomer, createCustomerSupplier, updateCustomer } from "../api/customers";
import { createSupplier, updateSupplier } from "../api/suppliers";
import { createEmployee, updateEmployee } from "../api/employees";
import { createWorker, updateWorker } from "../api/workers";
import { apiErrorMessage } from "../utils/pageHelpers";
const configs = { customer: { title: "إضافة عميل", submit: createCustomer, update: updateCustomer, fields: ["name", "phone", "email", "code", "openingBalance", "openingBalanceType"] }, supplier: { title: "إضافة مورد", submit: createSupplier, update: updateSupplier, fields: ["name", "phone", "email", "code", "openingBalance", "openingBalanceType"] }, both: { title: "إضافة عميل ومورد", submit: createCustomerSupplier, fields: ["name", "phone", "email", "code", "openingBalance", "openingBalanceType"] }, employee: { title: "إضافة موظف", submit: createEmployee, update: updateEmployee, fields: ["name", "code", "phone", "nationalId", "baseSalary", "department"] }, worker: { title: "إضافة عامل", submit: createWorker, update: updateWorker, fields: ["name", "code", "phone", "nationalId", "baseSalary", "commissionRate"] } };
const labels = { name: "الاسم", code: "الكود", phone: "رقم الهاتف", email: "البريد الإلكتروني", nationalId: "الرقم القومي", baseSalary: "المرتب الأساسي", openingBalance: "الرصيد الافتتاحي", openingBalanceType: "نوع الرصيد", commissionRate: "نسبة العمولة %", department: "القسم" };
export default function EntityModal({ type, entity, onClose, onSaved }) { const config = configs[type]; const [form, setForm] = useState({ name: entity?.name || "", code: entity?.code || "", phone: entity?.phone || "", email: entity?.email || "", nationalId: entity?.nationalId || "", baseSalary: entity?.baseSalary || "", openingBalance: entity?.openingBalance || "", openingBalanceType: entity?.openingBalanceType || (type === "supplier" ? "credit" : "debit"), commissionRate: entity?.commissionRate || "", department: entity?.department || "other" }); const [state, setState] = useState({ saving: false, error: "" }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const save = async (event) => { event.preventDefault(); setState({ saving: true, error: "" }); try { const payload = Object.fromEntries(Object.entries(form).filter(([, value]) => value !== "")); if (entity?._id && config.update) await config.update(entity._id, payload); else await config.submit(payload); onSaved?.(); onClose(); } catch (error) { setState({ saving: false, error: apiErrorMessage(error) }); } }; return <div className="modal-backdrop" onMouseDown={onClose}><form className="invoice-modal" onSubmit={save} onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">دليل البيانات</span><h2>{entity ? `تعديل ${config.title.replace("إضافة ", "")}` : config.title}</h2></div><button type="button" className="close-button" onClick={onClose}><X size={19} /></button></div>{state.error && <div className="page-error mt-4">{state.error}</div>}<div className="form-grid">{config.fields.map((field) => <div className="form-field" key={field}><label>{labels[field]}</label>{field === "openingBalanceType" ? <select value={form[field]} onChange={(event) => update(field, event.target.value)}><option value="debit">مدين</option><option value="credit">دائن</option><option value="none">بدون رصيد</option></select> : field === "department" ? <select value={form[field]} onChange={(event) => update(field, event.target.value)}><option value="other">أخرى</option><option value="management">الإدارة</option><option value="admin">إداري</option></select> : <input required={field === "name" || field === "code"} type={field === "email" ? "email" : ["baseSalary", "openingBalance", "commissionRate"].includes(field) ? "number" : "text"} value={form[field]} onChange={(event) => update(field, event.target.value)} placeholder={labels[field]} />}</div>)}</div><div className="modal-actions"><button className="primary-button" disabled={state.saving}>{state.saving ? "جارٍ الحفظ..." : entity ? "حفظ التعديل" : "حفظ البيانات"}</button><button type="button" className="secondary-button" onClick={onClose}>إلغاء</button></div></form></div>; }
